version: '3.3'

services:
  isso:
    build:
      context: ./src
      dockerfile: Dockerfile
    restart: always
    ports:
      - "8080:8080"
    volumes:
      - ./config:/config
      - ./database:/database
